#!/usr/bin/env python3
"""
mksdef.py -- generate the scripting dictionary and the schema artifact
from ui/metal.c's command table.

The table between SCRIPT-TABLE-BEGIN and SCRIPT-TABLE-END markers is
the single source of truth for the Apple Events surface
(riscos-pi4/SCRIPTING.md): the dispatch looks names up in it at runtime,
describe serialises it to callers, and this script parses it at build
time to write

    riscos-pi4/app/RISCOSQEMU.sdef   the scripting dictionary
    riscos-pi4/app/commands.json     the schema artifact for agent docs

the way tools/mkcmos.py parses RISC OS headers rather than transcribing
them.  The artifacts are committed, and make-bundle.sh re-runs this so a
stale sdef cannot ship.  XML comments may not contain double hyphens;
the generator never emits them, and the hand-written era's lesson is
recorded in SCRIPTING.md section 13.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

ENTRY = re.compile(
    r'\{\s*"([^"]+)",\s*"([^"]+)",\s*"([^"]*)",\s*(NULL|"(?:[^"]*)"),\s*\'([fb])\'\s*\}'
)


def parse_table(text):
    m = re.search(r"SCRIPT-TABLE-BEGIN(.*)SCRIPT-TABLE-END", text, re.S)
    if not m:
        sys.exit("mksdef.py: no SCRIPT-TABLE markers in ui/metal.c")
    cmds = []
    for name, code, help_, args, klass in ENTRY.findall(m.group(1)):
        if len(code) != 8:
            sys.exit(f"mksdef.py: code {code!r} is not eight characters")
        cmds.append({
            "name": name,
            "code": code,
            "help": help_,
            "args": None if args == "NULL" else args.strip('"'),
            "class": "fast" if klass == "f" else "bottom",
        })
    if not cmds:
        sys.exit("mksdef.py: the command table is empty")
    suites = {c["code"][:4] for c in cmds}
    if len(suites) != 1:
        sys.exit(f"mksdef.py: mixed suites in the table: {sorted(suites)}")
    return suites.pop(), cmds


def xml_escape(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


def write_sdef(path, suite, cmds):
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE dictionary SYSTEM "file://localhost/System/Library/DTDs/sdef.dtd">',
        "<!--",
        "  RISCOSQEMU.sdef: the scripting dictionary.",
        "",
        "  GENERATED by riscos-pi4/tools/mksdef.py from the command table in",
        "  ui/metal.c; edit the table, not this file.  The suite code is mixed",
        "  case because Apple reserves all-lowercase codes, and XML comments",
        "  may not contain double hyphens, which is why this comment reads",
        "  the way it does.  See riscos-pi4/SCRIPTING.md.",
        "-->",
        '<dictionary xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"',
        '            xs:schemaLocation="file://localhost/System/Library/DTDs/sdef.xsd"',
        '            title="RISCOSQEMU">',
        "\t<suite name=\"RISC OS QEMU suite\" code=\"%s\" "
        "description=\"Controlling and debugging the emulated machine.\">" % suite,
    ]
    for c in cmds:
        lines += [
            "\t\t<command name=\"%s\" code=\"%s\" description=\"%s\">"
            % (c["name"], c["code"], xml_escape(c["help"])),
            "\t\t\t<direct-parameter>",
            "\t\t\t\t<type type=\"text\" optional=\"yes\" "
            "description=\"A JSON command object; omitted means ping.\"/>",
            "\t\t\t</direct-parameter>",
            "\t\t\t<result>",
            "\t\t\t\t<type type=\"text\" description=\"The JSON reply envelope.\"/>",
            "\t\t\t</result>",
            "\t\t</command>",
        ]
    lines += [
        "\t</suite>",
        "</dictionary>",
    ]
    path.write_text("\n".join(lines) + "\n")


def write_schema(path, suite, cmds):
    doc = {
        "surface": 1,
        "suite": suite,
        "reply": "JSON envelope: {ok, data | error, elapsed_ms, machine}",
        "commands": cmds,
    }
    path.write_text(json.dumps(doc, indent=2, sort_keys=False) + "\n")


def main():
    src = (ROOT / "ui" / "metal.c").read_text()
    suite, cmds = parse_table(src)
    write_sdef(ROOT / "riscos-pi4" / "app" / "RISCOSQEMU.sdef", suite, cmds)
    write_schema(ROOT / "riscos-pi4" / "app" / "commands.json", suite, cmds)
    names = ", ".join(c["name"] for c in cmds)
    print(f"mksdef.py: suite {suite}, {len(cmds)} commands: {names}")


if __name__ == "__main__":
    main()
