#!/bin/sh
# Build the HostNet module: Internet 6.00, the guest half of host-side
# sockets.  Same toolchain and runtime as build-hostfs.sh next door --
# roscc's module linker, clang for ARM, the rostrt runtime -- because the
# module has to run from ROM, and cmhg's header and the C stubs both write
# into the module image at initialisation, which from ROM is a data abort.
#
# The SWI list is generated from swis.txt rather than typed, so the order
# cannot drift from the Internet module's decoding table
# (Networking/AUN/Internet/build/cmhg/InetHdr).  Both the module header and
# the C entry points come from that one list.
set -e
cd "$(dirname "$0")"

LLVM="/c/Program Files/LLVM/bin"
ROSCC="/f/RISCOSDEV/compiler/target/debug/roscc.exe"
GEN="/f/RISCOSDEV/compiler/tools/gen_module.py"
RTRT="/f/RISCOSDEV/compiler/rostrt"
TRIPLE=armv8a-none-eabi
CPU=cortex-a72
OUT=build

VERSION="6.00"
DATE="14 Sep 2026"

# ROSTRT_STATIC_HEAP because this is a module: it has no application slot
# to grow a heap into, so the runtime uses static arrays instead of the
# _end..memory-limit gap.  They are tiny on purpose -- HostNet allocates
# nothing: every request goes in one static block, and every buffer it
# touches belongs to the caller.
ARENAS="-DROSTRT_STATIC_HEAP -DHEAP_BYTES=1024 -DARENA_BYTES=256"
CC_FLAGS="--target=$TRIPLE -mcpu=$CPU -mfloat-abi=soft -ffreestanding \
-nostdlib -fno-builtin -fropi -frwpi -O2 -mno-movt $ARENAS"

mkdir -p "$OUT"

echo "== SWI list -> header arguments and C entry points"
python - <<'PY'
names = [n for n in open('swis.txt').read().split() if n]
nl = chr(10)
open('hostnet_swis.inc', 'w').write(
    '/* Generated by build-hostnet.sh from swis.txt -- do not edit.' + nl +
    ' * One entry point per socket SWI, in chunk order from &41200.' + nl +
    ' * Each is a veneer target: it does nothing but name its own number. */'
    + nl +
    nl.join(f'HN_ENTRY({i:02d}, {i})  /* Socket_{n} */'
            for i, n in enumerate(names)) + nl)
open('build/swi-args.txt', 'w').write(
    ' '.join(f'--swi "{n}:hn_swi_{i:02d}"' for i, n in enumerate(names)))
print(f"   {len(names)} SWIs, &41200-&{0x41200 + len(names) - 1:X}")
PY

echo "== header + module veneers"
# Title "Internet", so that every RMEnsure Internet on the disc is
# satisfied without a single edit; the ROM's 5.67 is unplugged in CMOS.
eval python "$GEN" \
    --title Internet \
    --help-text "'HostNet\\t$VERSION ($DATE)'" \
    --rwpi \
    --init hostnet_init --final hostnet_final \
    --command "'HostNetPing:hostnet_command_ping:0:0:*HostNetPing asks the host if it is there\\rSyntax:\\t*HostNetPing'" \
    --swi-chunk 0x41200 --swi-prefix Socket \
    $(cat "$OUT/swi-args.txt") \
    --arch armv8a \
    -o "$OUT/module_head.s"

"$LLVM/clang.exe" $CC_FLAGS -c "$OUT/module_head.s" -o "$OUT/module_head.o"

echo "== module body"
"$LLVM/clang.exe" $CC_FLAGS -c hostnet.c -o "$OUT/hostnet.o"

echo "== runtime"
for src in rostrt.c swis_os.c modrt.c; do
    "$LLVM/clang.exe" $CC_FLAGS -c "$RTRT/$src" -o "$OUT/${src%.c}.o"
done
"$LLVM/clang.exe" --target=$TRIPLE -mcpu=$CPU -mfloat-abi=soft \
    -c "$RTRT/aeabi.s" -o "$OUT/aeabi.o"
"$LLVM/clang.exe" --target=$TRIPLE -mcpu=$CPU -mfloat-abi=soft \
    -c "$RTRT/atomics_swp.s" -o "$OUT/atomics.o"

echo "== link"
"$ROSCC" link --module -o "$OUT/HostNet,ffa" \
    "$OUT/module_head.o" "$OUT/hostnet.o" \
    "$OUT/rostrt.o" "$OUT/swis_os.o" "$OUT/modrt.o" \
    "$OUT/aeabi.o" "$OUT/atomics.o"

ls -l "$OUT/HostNet,ffa"
